package scad

import "fmt"

// Symbol/variable names within SCAD code
const (
	prefix  = "__s2s_" // Uniqifier for ensuring no name collisions with user-defined symbols
	CURSOR  = "cursor" // cursor is always local scope and needs no prefix
	EXTENTS = prefix + "extents"
)

const LibSubdir = "lib"
const LibFilename = "svg2scad.scad"

var Imports = []string{
	"include <BOSL2/beziers.scad>",
	"include <BOSL2/std.scad>",
	fmt.Sprintf("include <%s/%s>", LibSubdir, LibFilename)}

var LibFileData = []byte(fmt.Sprintf(
	`// CODEGEN: This file was GENERATED by svg2scad and SHOULD NOT BE MODIFIED by hand.

// Finds the bounding box of a set of 2D coordinates
function %[1]s(coords, largest = [ -1e9, -1e9 ], smallest = [ 1e9, 1e9 ]) =
    len(coords) == 0 ? [ largest, smallest ]
                     : %[1]s(list_tail(coords),
                               [ max(largest[0],  coords[0][0]), max(largest[1],  coords[0][1]) ],
                               [ min(smallest[0], coords[0][0]), min(smallest[1], coords[0][1]) ]);

`, EXTENTS))
