package scad

import "fmt"

const LibSubdir = "lib"
const LibFilename = "svg2scad.scad"

var Imports = []string{
	"include <BOSL2/beziers.scad>",
	"include <BOSL2/std.scad>",
	fmt.Sprintf("include <%s/%s>", LibSubdir, LibFilename)}

const extentsFunctionName = "svg2scad_extents"

var LibFileData = []byte(fmt.Sprintf(
	`// CODEGEN: This file was GENERATED by svg2scad and SHOULD NOT BE MODIFIED by hand.

// Finds the bounding box of a set of 2D coordinates
function %s(coords, largest = [ -1e9, -1e9 ], smallest = [ 1e9, 1e9 ]) =
    len(coords) == 0 ? [ largest, smallest ]
                     : %s(list_tail(coords),
                               [ max(largest[0],  coords[0][0]), max(largest[1],  coords[0][1]) ],
                               [ min(smallest[0], coords[0][0]), min(smallest[1], coords[0][1]) ]);

`, extentsFunctionName, extentsFunctionName))
